version: "3.7"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: clientes
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  api:
    container_name: api
    volumes:
      - ./api:/var/www/html
    build: ./images/php
    working_dir: /var/www/html/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./images/nginx
    volumes:
      - ./api:/var/www/html
    command: nginx -g "daemon off;"
    links:
      - api
    ports:
      - "80:80"
    depends_on:
      - db

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ../images/vue/Dockerfile
    expose:
       - 8081
    volumes:
      - ./client:/app
    working_dir: /app/dist
    links:
      - api:api
    ports:
      - "8081:8081"
    depends_on:
      - api
